### ISSUE TITLE
java 8 compile error on android 

### ISSUE THREAD

**Issue by lulumeya** [evant/gradle-retrolambda#102]
My project fails build on Windows environment, but works on Mac.
The error message is here!

22:07:06.547 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
22:07:07.956 [ERROR] [system.err] An exception has occurred in the compiler (1.8.0_45). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the foll
owing diagnostic in your report.  Thank you. 
22:07:07.960 [ERROR] [system.err] com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
22:07:07.964 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:_compileUserReleaseJava'
22:07:07.967 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:_compileUserReleaseJava FAILED
22:07:07.970 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:_compileUserReleaseJava (Thread[main,5,main]) completed. Took 1.547 secs.
22:07:07.972 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 25.62 secs, idle: 0.228 secs
22:07:07.980 [ERROR] [org.gradle.BuildExceptionReporter]
22:07:07.984 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
22:07:07.989 [ERROR] [org.gradle.BuildExceptionReporter]
22:07:07.991 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
22:07:07.994 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:_compileUserReleaseJava'.
22:07:07.997 [ERROR] [org.gradle.BuildExceptionReporter] > Compilation failed; see the compiler error output for details.
22:07:08.000 [ERROR] [org.gradle.BuildExceptionReporter]
22:07:08.002 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
22:07:08.005 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:_compileUserReleaseJava'.
22:07:08.007 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
22:07:08.009 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
22:07:08.011 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
22:07:08.013 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
22:07:08.015 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
22:07:08.017 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
22:07:08.021 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
22:07:08.024 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
22:07:08.027 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
22:07:08.029 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
22:07:08.031 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
22:07:08.033 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
22:07:08.035 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
22:07:08.037 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
22:07:08.038 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
22:07:08.040 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
22:07:08.042 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
22:07:08.044 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
22:07:08.046 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
22:07:08.048 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
22:07:08.051 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
22:07:08.053 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
22:07:08.057 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
22:07:08.059 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
22:07:08.061 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
22:07:08.063 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
22:07:08.065 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
22:07:08.067 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
22:07:08.069 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
22:07:08.070 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
22:07:08.072 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
22:07:08.074 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
22:07:08.076 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
22:07:08.077 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
22:07:08.079 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
22:07:08.081 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
22:07:08.085 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
22:07:08.087 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
22:07:08.088 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
22:07:08.090 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
22:07:08.092 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
22:07:08.094 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
22:07:08.096 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
22:07:08.098 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
22:07:08.099 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
22:07:08.101 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
22:07:08.103 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
22:07:08.105 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:55)
22:07:08.107 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
22:07:08.109 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:44)
22:07:08.110 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
22:07:08.112 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:97)
22:07:08.116 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
22:07:08.118 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
22:07:08.120 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
22:07:08.122 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
22:07:08.124 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:158)
22:07:08.126 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:138)
22:07:08.128 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:92)
22:07:08.130 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
22:07:08.132 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
22:07:08.133 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
22:07:08.136 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
22:07:08.138 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
22:07:08.140 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
22:07:08.142 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
22:07:08.144 [ERROR] [org.gradle.BuildExceptionReporter]        ... 47 more
22:07:08.147 [ERROR] [org.gradle.BuildExceptionReporter]
22:07:08.149 [LIFECYCLE] [org.gradle.BuildResultLogger]
22:07:08.161 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED

my build script is here!

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'me.tatarka:gradle-retrolambda:3.0.1'
        classpath "com.android.tools.build:gradle:" + project.plugin_version
    }
}

apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'com.android.application'

def buildTime = new Date().format("MMdd-HHmm")

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileSdkVersion 22
    buildToolsVersion '22.0.0'

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java']
            resources.srcDirs = ['src/main/java']
            aidl.srcDirs = ['src/main/java/aidl']
            renderscript.srcDirs = ['src/main/rs']
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['src/main/assets']
        }

        user {
            res.srcDirs = ['src/env/user/res']
        }

        admin {
            res.srcDirs = ['src/env/admin/res']
        }

        androidTest.setRoot('tests')
    }

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 22
        versionCode 30
        versionName "0.999"
        // Enabling multidex support.
        multiDexEnabled true
    }

    signingConfigs {
        debug {
            storeFile file("key/debug.keystore")
        }

        release {
            storeFile file("key/healingpaper.keystore")
            keyAlias "**"
            storePassword "**"
            keyPassword "**"
            // storePassword System.in.readLine("\nKeystore password: ")
            // keyPassword System.in.readLine("\nKey password: ")
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
            applicationIdSuffix ".debug"

        }

        release {
            minifyEnabled true
            shrinkResources true
            debuggable false
            signingConfig signingConfigs.release
            proguardFile file("proguard-rules.txt")
            // proguardFile getDefaultProguardFile('proguard-android.txt')

            // when not specified will it use default?
            // proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }

        productFlavors {
            user {
                applicationId = "com.gangnam.sister"
            }

            admin {
                applicationId = "com.gangnam.sister.hospital"
            }
        }
    }

    lintOptions {
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
        exclude 'AndroidManifest.xml'

        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
        exclude 'META-INF/NOTICE'
    }

    applicationVariants.all { variant ->
        appendVersionNameVersionCode(variant, "${variant.versionName}-${buildTime}")
    }

    task removeResources(dependsOn: 'lint') << {
        def issues = new XmlParser().parse(file("$buildDir/outputs/lint-results.xml"))
        assert issues
        def locations = issues.issue.location.findAll { it.parent().'@id' == 'UnusedResources' }
        def strings = locations.grep { it.'@line' }.'@file'*.toString()
        def res = locations.grep { !it.'@line' }.'@file'*.toString()
        println '-' * 10 + 'not used string (this feature is currently under development..)' + '-' * 10
        strings.each {
            println it
        }
        println '-' * 10 + 'not used res(png , xml , jpg , etc...)' + '-' * 10
        res.each {
            //I can't solve some xml problem. so ignore '.xml'.
            //Sometimes it's not referred by file name, but it's referred by id.
            //ex) 'foo.xml' --> not used
            // but in 'foo.xml' android:id="@+id/bar" is referred like '@id/bar'
            if (!it.endsWith('.xml')) {
                file(it).delete()
                println "${it} deleted."
            }
        }
    }
}

def appendVersionNameVersionCode(variant, replace) {
    //check if release variant
    if (variant.buildType.name == android.buildTypes.release.name) {
        variant.outputs.each { output ->
            def file = output.outputFile
            def fileName = file.name.replace(".apk", "-" + replace + ".apk")
            output.outputFile = new File(file.parent, fileName)
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile 'com.android.support:support-v4:22.1.+'
    compile 'com.android.support:appcompat-v7:22.1.+'
    compile 'com.android.support:recyclerview-v7:+'
    compile 'com.android.support:cardview-v7:22.+'
    compile 'com.google.android.gms:play-services:6.1.+'

    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.mcxiaoke.volley:library:1.0.10'
    compile 'com.github.bumptech.glide:glide:3.3.+'
    compile 'com.jakewharton:butterknife:6.0.0'
    compile 'com.github.chrisbanes.photoview:library:1.2.3'
    compile('com.viewpagerindicator:library:2.4.1@aar') {
        exclude module: 'support-v4'
    }
    compile 'com.facebook.android:facebook-android-sdk:3.21.1'
    compile 'com.firebase:firebase-client-android:2.2.1+'
    compile 'com.yqritc:recyclerview-flexibledivider:1.1.0'
    compile 'jp.wasabeef:recyclerview-animators:1.1.2@aar'
    compile 'net.kianoni:fontloader:0.3.0'
    compile 'com.githang:com-phillipcalvin-iconbutton:1.0.1@aar'

    compile 'io.reactivex:rxandroid:0.24.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.wdullaer:materialdatetimepicker:1.2.2'
}

What can I do now?

**Comment by evant** [comment]
Looks like something isn't right with the classpath it's compiling with. Are you sure you have the JAVA8_HOME env variable set correctly? Try running with `--debug` and checking the classpath in "Compiler arguments:" to see if it's adding it.

**Comment by lulumeya** [comment]
@evant 
Thanks, I set env already, but haven't below config
retrolambda {
    jdk System.getenv("JAVA8_HOME")
}
I set this config, It works!

**Comment by evant** [comment]
Hm, that should be the default. Might have to look into why it's not being picked up correctly in some cases.
