### ISSUE TITLE
Retrolambda version 3.1.0 doesn't work

### ISSUE THREAD

**Issue by ultraon** [evant/gradle-retrolambda#108]
Hi, today i updated retrolambda from 3.0.1 to 3.1.0 and i have a lot of troubles.
All compile tasks work very slow and main module of my project isn't compiled, i don't see any errors in gradle console but compile task is never finished.
So with 3.0.1 my project compiles 3 min, with 3.1.0 - never.
(Additionally I use Dagger2, AndroidAnnotations, Otto Bus and other libs with code-generator)
Help please.

**Comment by evant** [comment]
Can you run with --info and see exactly where it's getting stuck?

**Comment by ultraon** [comment]
Hi, i made a lot of experiments with different configuration of build.gradle, made compilation with --info, but there is no interesting messages with errors. I saw only fact that compile (or assemble) tasks are very slow:
```
retrolambda 3.1.0 (with google play service (location) lib):
Executing tasks: [clean, :application:compileDebugSources, :data:compileDebugSources, :mock:compileDebugSources, :presentation:compileDebugSources, :process:compileDebugSources, :transport:compileDebugSources]
=> 1 hrs 40 mins 32.718 secs

retrolambda 3.0.1 (with google play service (location) lib):
Executing tasks: [clean, :application:compileDebugSources, :data:compileDebugSources, :mock:compileDebugSources, :presentation:compileDebugSources, :process:compileDebugSources, :transport:compileDebugSources]
=> 27.856 secs
```

**Comment by ultraon** [comment]
Also i found that task compileDebugAndroidTestJava with google play services (7.3) in library module is never completed (used with retrolambda 3.0.1), i was waiting for 10 mins.

**Comment by ultraon** [comment]
When i remove plugin retrolambda and refactor my project it works well and fast, building time now is 1 mins 16.981 secs for command:
```
./gradlew clean assemble
```

So the problem is:
1. retrolambda (3.0.1) + google play services 7.3 in library module;
2. retrolambda (3.1.0) -> slow compile task execution (2 times slower);
3. retrolambda (3.0.1 & 3.1.0) -> problem with compileDebugAndroidTestJava task;

**Comment by evant** [comment]
Mind trying with `3.2.0`? I realized that the check for running the java agent wasn't workig correctly for retrolambda `2.x`, which may have caused the longer build times.

**Comment by v1shnu** [comment]
@evant : With `3.2.0`, the build is still getting stuck at: `:module-name:compileRetrolambdaRelease`.
Things work fine with `3.0.1`.

**Comment by jjvargas** [comment]
Same thing for me, it gets stuck with 3.2.0 and works for 3.0.1 I am using Dagger2, Android Annotations, Otto, and the Mosby Framework which has some libs that generate code.

**Comment by ashoykh** [comment]
We ran into the same issue and traced it back to `https://issues.gradle.org/browse/GRADLE-3283`.

The problematic set of code is in gradle itself in `org/gradle/execution/taskgraph/DefaultTaskExecutionPlan.java -> enforceFinalizerTasks` and `enforceWithDependencies`

Retrolambda sets itself as the finalizer for the java compile task.  The enforceWithDependencies task run time increases exponentially with the depth of the dependency tree.  The real fix should be in gradle itself.  In the meantime, we're using 3.0.1.

**Comment by evant** [comment]
Ah! That's good to know! I'm currently working on migrating to a new mechanism that won't have this issue: https://github.com/evant/gradle-retrolambda/issues/129 though it requires the android gradle plugin `1.4.0` which isn't out of beta yet.

**Comment by evant** [comment]
I've attempted to apply the advice in the gradle issue and removed the retrolambda task dependency on the javaCompile task in hopes it doesn't have to do another dependency traversal. I don't currently have a large project I can test this on, but I've pushed it up as `3.2.3-SNAPSHOT` (on https://oss.sonatype.org/content/repositories/snapshots) if anyone wants to check it out.

This will cause the retrolamba task not to work if run directly, (you will have to run the javacompile task instead) will that cause issues for anyone?

**Comment by r4zzz4k** [comment]
Thanks, Evan! I had the same problem like described above, so I had to use `3.0.1`. I've tried switching to `3.2.3-SNAPSHOT` and it's working again. I appreciate your work!

**Comment by ashoykh** [comment]
Great, thanks Evan!  I created a pull request to gradle to fix the issue on their end - https://github.com/gradle/gradle/pull/525

In the meantime, 3.2.3-SNAPSHOT works great for us.  Thanks!

**Comment by evant** [comment]
Release `3.2.3` which works around this issue.

**Comment by twinkleSiya** [comment]
Hi, Good Morning.
    
   Please help me this warning..
    Warning:One of the plugins you are using supports Java 8 language features. To try the support built 
   into the Android plugin, remove the following from your build.gradle:
    
  apply plugin: 'me.tatarka.retrolambda'

All used dependency and Retro lambda classpath add in my gradle app, after this warning not remove
