### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by avenwu** [evant/gradle-retrolambda#112]
Hi, 
According to the "Usage", I have download the jdk8 and set JAVA8_HOME, however my AndroidStudio still failed to build the project; Any suggestion?
 
> Error:Execution failed for task ':app:compileDebugJava'.
> When running gradle with java 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

Below is my JAVA8_HOME and build.gradle
>aven-mac-pro:RxDemo aven$ echo $JAVA8_HOME
>/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
>aven-mac-pro:RxDemo aven$ echo $JAVA7_HOME
>/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home
>aven-mac-pro:RxDemo aven$ 

>retrolambda {
> jdk System.getenv("JAVA8_HOME")
>}

There is also jdk7 installed on my OSX before the jdk8 was installed

**Comment by evant** [comment]
It's likely AS isn't picking up  the environment variable. There are various work-arounds on https://github.com/evant/gradle-retrolambda/issues/61 that may help you.

**Comment by avenwu** [comment]
It worked.
I have remove the retrolambda config, and set JAVA8_HOME through AS prefence:
@pakoito 
I found a workaround by going to Android Studio -> Preferences -> Path Variables and adding

JAVA_8 /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
