### ISSUE TITLE
Generated files are not picked up in AndroidStudio/IntelliJ

### ISSUE THREAD

**Issue by mopsalarm** [evant/gradle-retrolambda#116]
I added (Immutables)[http://immutables.github.io/] to my android project and after compiling, it generated java and class files under `/app/build/retrolambda/openDebug` and the same classes but no souces under `/app/build/intermediates/classes/open/debug`. 
After deactivating the plugin, those files are generated only unter `/app/build/intermediates/classes/open/debug`.

Sadly AndroidStudio is not picking up the generated files - but gradle is. If i add reference the generated classes by fqn in my code, i can compile the app using `gradlew`, but AndroidStudio still marks those classes as missing.

**Comment by evant** [comment]
are you using android-apt to make AS able to see the generated files?

**Comment by mopsalarm** [comment]
Nope, I thought it wasn't necessary as just adding the library using 'provided' already created the class files. I will try that tomorrow, thank you

**Comment by evant** [comment]
Yeah, without it AS won't pick up the generated files, this has nothing to do with gradle-retrolamba

**Comment by mopsalarm** [comment]
Thank you very much, now everything worked. I am sorry that i bothered you with this problem!
