### ISSUE TITLE
Problems configuring RetroLambda

### ISSUE THREAD

**Issue by EveryNameTaken** [evant/gradle-retrolambda#117]
I never used RetroLambda before, i am missing something and can't find solution anywhere. (using Android Studio)

After adding this code:

    retrolambda {
      jdk System.getenv("JAVA8_HOME")
      oldJdk System.getenv("JAVA7_HOME")
      javaVersion JavaVersion.VERSION_1_7
      jvmArgs '-arg1', '-arg2'
      defaultMethods false
      incremental true
    }

i get an error: "invalid source release 1.8". After googling for some time, i found this code:

    retrolambda {
        jdk '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home'
        oldJdk System.getenv("JAVA7_HOME")
        javaVersion JavaVersion.VERSION_1_7
}

and this will compile, but when i select android device and run i get Unexpected Error: Local path doesn't exist. I experimented with Path Variables in settings, not sure if they do anything.

**Comment by evant** [comment]
Please check https://github.com/evant/gradle-retrolambda/issues/61 for solutions for getting AS to see the environment variables.

**Comment by EveryNameTaken** [comment]
OK, it works now. I had the retrolambda { jdk, oldJdk} code in wrong .gradle file whole time.

It was in build.gradle (Module: app), so i moved it to build.gradle(Project: project_name).
