### ISSUE TITLE
default methods work when they shouldnt

### ISSUE THREAD

**Issue by talarari** [evant/gradle-retrolambda#122]
hey,
i want to add retrolambda to a project i'm working on, i wanted to check what happens if i use an unsupported feature of java 8 (which is not backported) , will it fail at runtime or build time?

if the failure is at build time its fine, runtime is a big problem.

so i created a sample app and tried using default methods without enabling them, expecting it to fail somehow, but it just worked. 
why is that? i see the project readme says its disabled by default , i also printed retrolambda.defaultMethods and it is indeed false

**Comment by talarari** [comment]
here's the sample app:
https://github.com/talarari/Retrolambdatest

**Comment by evant** [comment]
A couple things to try: try running with --info and check the retrolambda command to see if its wrongly enabling default methods. You can also try forcing and earlier version of retrolambda with retrolamdaConfig to see if it changed in a more recent version. The README for retrolambda makes no mention of it being enabled by default but maybe it is.

**Comment by evant** [comment]
Ok the is really strange. I _still_ works even if I go back to retrolambda `1.1.2` which is before default methods was even implemented in retrolambda. I've also tried decompiling `SomeInterface.class` in the generated aar using intellij's built-in decompiiler and it clearly shows the static and default methods even though the message at the top is "Decompiled .class file, bytecode version 51.0 (Java 7)". @orfjackal any idea what's going on?

**Comment by orfjackal** [comment]
It should fail at runtime, typically when loading the class on an earlier JVM, or when executing the code that uses those features or APIs.

@evant, Retrolamdba has changed the bytecode version number of the .class file, but hasn't backported the static and default methods, so they are still in the bytecode. That class should produce an error when the class loader tries to load and validate it, because Java 7 bytecode should not have static and default methods on interfaces.

**Comment by evant** [comment]
But its not, it's working fine at runtime. Feel free to check yourself with the sample project.

**Comment by evant** [comment]
Alright, I've partially figured out what is going on. This _only_ works on lollipop. On older versions it will fail at runtime with `java.lang.VerifyError: com/asurion/retrolib/OtherClass`. It seems like verification has been relaxed for some reason, possibley due to the switch to aot compiliation with ART?

**Comment by cypressious** [comment]
Next you gonna tell me, lambdas work out of the box on Lollipop?

**Comment by evant** [comment]
@cypressious sorry, dx doesn't like it
```
Unknown source file : com.android.dx.cf.iface.ParseException: MethodHandle not supported
Unknown source file : 	at com.android.dx.cf.cst.ConstantPoolParser.determineOffsets(ConstantPoolParser.java:220)
Unknown source file : 	at com.android.dx.cf.cst.ConstantPoolParser.parse(ConstantPoolParser.java:132)
Unknown source file : 	at com.android.dx.cf.cst.ConstantPoolParser.parseIfNecessary(ConstantPoolParser.java:124)
Unknown source file : 	at com.android.dx.cf.cst.ConstantPoolParser.getPool(ConstantPoolParser.java:115)
Unknown source file : 	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:482)
Unknown source file : 	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
Unknown source file : 	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
Unknown source file : 	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
Unknown source file : 	at com.android.dx.command.dexer.Main.processClass(Main.java:665)
Unknown source file : 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
Unknown source file : 	at com.android.dx.command.dexer.Main.access$600(Main.java:78)
Unknown source file : 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
Unknown source file : 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
Unknown source file : 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
Unknown source file : 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
Unknown source file : 	at com.android.dx.command.dexer.Main.processOne(Main.java:596)
Unknown source file : 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:230)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:199)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:103)
Unknown source file : ...while preparsing cst 001a at offset 00000235
Unknown source file : ...while parsing com/asurion/retrolib/SomeClass.class
```

**Comment by talarari** [comment]
great, thanks for looking into this.
so basically any non backported java8 features will fail at run time? is there no way of making it fail on build?

**Comment by orfjackal** [comment]
You could write a Java program which iterates through all the class files in the project and tries to load each of them (using `ClassLoader.loadClass`). That should give 80% confidence in it working (it won't detect the use of Java 8 APIs due to the laziness of class loading). For better confidence your program needs tests with good coverage (which it anyways should have).

**Comment by talarari** [comment]
@orfjackal  it seems like i cant access any java 8 api , (like java.util.functions or java.util.stream) on an android project, probably because these packages dont exist in the android sdk right?
so basically i only have to be careful with java.util.lang java 8 features like default methods?

**Comment by orfjackal** [comment]
That's right, you can't use any methods or classes that don't exist on Android.
