### ISSUE TITLE
Running Junit tests results in errors

### ISSUE THREAD

**Issue by patrykpoborca** [evant/gradle-retrolambda#123]
I'm trying to set up some Junit tests, however it appears that Retrolambda is breaking my testCompile. This is the error I'm getting: Is there a way to set up junit tests that utilize retrolambda? Cause as of now I cannot figure it out, even though it appears I haven't done anything wrong and this error was supposed to have been patched out?

```An exception has occurred in the compiler (1.8.0_40). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found```

Here's my build.gradle: https://github.com/patrykpoborca/CleanArchitecture/blob/feature/nested-unit-testing/app/build.gradle

My repo is here: https://github.com/patrykpoborca/CleanArchitecture/tree/feature/nested-unit-testing

**Comment by jjvargas** [comment]
Try with Retrolambda 3.0.1 to see if it works.

**Comment by patrykpoborca** [comment]
@jjvargas It seems like 3.2.2 worked for me... wow. I thought I had the newest version! Thanks, sorry for the trouble, I'll let you know if anything breaks!

**Comment by evant** [comment]
Probably a dup of https://github.com/evant/gradle-retrolambda/issues/120 then.
