### ISSUE TITLE
Invalid source release

### ISSUE THREAD

**Issue by schwiz** [evant/gradle-retrolambda#124]
Trying to build an android application on mac. I have added the following to my build.gradle

```groovy
retrolambda {
    println("***************** ---------- *******************")
    println("JAVA_HOME: " + System.getenv("JAVA_HOME"))
    println("JAVA7_HOME: " + System.getenv("JAVA6_HOME"))
    println("JAVA8_HOME: " + System.getenv("JAVA8_HOME"))
    println("***************** ---------- *******************")
}
```

I get this output when building.
```
***************** ---------- *******************
JAVA_HOME: /System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
JAVA7_HOME: /System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
JAVA8_HOME: /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home
***************** ---------- *******************


Error:javac: invalid source release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options
```

**Comment by evant** [comment]
You sure /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home is java 8?

**Comment by schwiz** [comment]
Oh this does seem to be the problem. I installed jdk8 from here http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
It didn't give an error but typing `which java` shows that I must be using some other version of java. I'm not sure where the oracle version got installed...

**Comment by schwiz** [comment]
Okay turns out the oracle install location on OSX is /Library/Java/JavaVirtualMachines/<sdkname> had to update my JAVA8_HOME variable accordingly. Thanks for pointing out my old version.
