### ISSUE TITLE
Method references are not taken into account by proguard

### ISSUE THREAD

**Issue by denis-itskovich** [evant/gradle-retrolambda#142]
I'm not sure whether it's an issue of `retrolambda` itself or `gradle-retrolambda`
#### Background

Proguard seems to shrink methods, referenced as method references. See an example below:

``` java
public class AsyncTaskBuilder<Progress, Result> {

    public interface BackgroundWorkWithProgress<_Progress, _Result> {
        _Result execute(ProgressObserver<_Progress> progressObserver);
    }

    private BackgroundWorkWithProgress<Progress, Result> work;

    public AsyncTask<Void, Progress, Result> build() {

        return new AsyncTask<Void, Progress, Result>() {
            @Override
            protected Result doInBackground(Void... voids) {
                // this reference will not be taken into account by Proguard
                return work.execute(this::publishProgress);
            }

        };
    }
}
```

After building, the following error is shown:

```
:app:proguardRelease
Warning: com.github.retrolambda_methodref_repro.AsyncTaskBuilder$1$$Lambda$1: can't find referenced method 'void publishProgress(java.lang.Object[])' in library class android.os.AsyncTask
Warning: there were 1 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
Exception while processing task 
java.io.IOException: Please correct the above warnings first.
    at proguard.Initializer.execute(Initializer.java:473)
    at proguard.ProGuard.initialize(ProGuard.java:233)
    at proguard.ProGuard.execute(ProGuard.java:98)
    at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)
    at com.android.build.gradle.tasks.AndroidProGuardTask.doMinification(AndroidProGuardTask.java:139)
    at com.android.build.gradle.tasks.AndroidProGuardTask$1.run(AndroidProGuardTask.java:115)
    at com.android.builder.tasks.Job.runTask(Job.java:48)
    at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
    at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:227)
    at java.lang.Thread.run(Thread.java:745)
```

Full log is available at [travis-ci](https://travis-ci.org/denis-itskovich/retrolambda-method-ref-repro/builds/85513111)
#### Sample android project

Simple android project (with 1 class), reproducing the issue can be found here:
[https://github.com/denis-itskovich/retrolambda-method-ref-repro](https://github.com/denis-itskovich/retrolambda-method-ref-repro)
#### Related issues

The issue seems to be related to this retrolambda issue: [https://github.com/orfjackal/retrolambda/issues/48](https://github.com/orfjackal/retrolambda/issues/48)

**Comment by orfjackal** [comment]
The log has some warnings about "AsyncTaskBuilder.java uses unchecked or unsafe operations." Does fixing those help?

**Comment by denis-itskovich** [comment]
Fixed the warning (replaced varargs generic parameter by generic array parameter), but the issue still exists: [https://travis-ci.org/denis-itskovich/retrolambda-method-ref-repro/builds/85513111](https://travis-ci.org/denis-itskovich/retrolambda-method-ref-repro/builds/85513111)

**Comment by gmarizy** [comment]
In my case, method references were causing failure even with proguard disabled, with error like:
```
E/AndroidRuntime: java.lang.NoClassDefFoundError: java.util.Objects
```
The reason was incompatibility with [gradle-errorprone-plugin](https://github.com/tbroyer/gradle-errorprone-plugin). Given that this plug-in play with compiler it's not that a surprise. It used to work with previous version of gradle-retrolambda though.

**Comment by konmik** [comment]
Did you try using the latest retrolambda version?

```
dependencies {
    retrolambdaConfig 'net.orfjackal.retrolambda:retrolambda:2.0.6'
```

**Comment by denis-itskovich** [comment]
Recently tried - getting the same error with 2.0.6

**Comment by duckinferno** [comment]
I'm getting this same error with 3.3.0-beta4.

**Comment by formatBCE** [comment]
Getting NoClassDefFound error on java.utils.Objects on both latest stable and 3.3.0 beta versions.
Could you please fix that?

**Comment by evant** [comment]
You need to update to the latest retrolamba, see https://github.com/orfjackal/retrolambda/issues/75

**Comment by formatBCE** [comment]
Same issue: **java.lang.NoClassDefFoundError: java.util.Objects**
build.gradle: **classpath 'me.tatarka:gradle-retrolambda:3.2.5'**

**Comment by evant** [comment]
You did
```
dependencies {
    retrolambdaConfig 'net.orfjackal.retrolambda:retrolambda:2.3.0'
}
```
correct?

**Comment by formatBCE** [comment]
I'm TRULY sorry...
Works! :)

**Comment by sunny-chung** [comment]
Reproducible in an Android project with
gradle-retrolambda 3.2.5 + retrolambda 2.3.0/2.4.0/2.5.0
gradle-retrolambda 3.5.0 + retrolambda 2.5.0,

apply plugin: 'me.tatarka.retrolambda' is put at the last.

This plugin was working at past time.

**Comment by ncruces** [comment]
Ignoring these warnings is enough to fix it:
```
-dontwarn **$$Lambda$*
```
