### ISSUE TITLE
Plugin does not work with Android test module "com.android.test"

### ISSUE THREAD

**Issue by forkch** [evant/gradle-retrolambda#146]
It should run the same process of retrolambda for Android Testmodules. Otherwise the compiled classes stay in Java 8 format and DEX can not process them.

**Comment by vRallev** [comment]
Running into the same issue. That's a showstopper for me.

**Comment by programmerdave** [comment]
I believe this was already resolved no? I have it working just fine with tests and connected android tests.

**Comment by vRallev** [comment]
With an Android test module? I mean a separate module with `apply plugin: 'com.android.test'`.

**Comment by evant** [comment]
@programmerdave The status of this ticket is accurate, support for the` 'com.android.test'` plugin is not currently implemented.

**Comment by evant** [comment]
Fixed in `3.4.0`
