### ISSUE TITLE
Support for pure Java modules 

### ISSUE THREAD

**Issue by adnan-SM** [evant/gradle-retrolambda#147]
I can't seem to be able to use retrolambda in modules which are purely Java based. The dependency compiles but I cant use lambdas within my code. 

Does the library support this ? Or am I missing something ?

**Comment by evant** [comment]
What error are you getting? It is supposed to work on a plain java module.

**Comment by adnan-SM** [comment]
Interesting, I added the retrolambda.jdk property and it builds. But lint still sees it as an error and complains lambdas are not supported at this language level. The autocomplete doesn't work either but the project compiles and runs fine.

**Comment by evant** [comment]
Sounds like you just need to change the language level, in intellij it's Project Structure >

**Comment by evant** [comment]
Sorry for the delay, those sound like IDE issues. Check the README on how to deal with Android Studio and lint. Feel free to reopen if you are still having issues.
