### ISSUE TITLE
Gradle build in Android Studio fails for com.android.library project

### ISSUE THREAD

**Issue by cheneric** [evant/gradle-retrolambda#149]
### Error

```
An exception has occurred in the compiler (1.8.0_60). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the database for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
```

### Background

Seems like https://github.com/evant/gradle-retrolambda/issues/15 fixed this issue for the Gradle command-line build, but I am encountering this issue in the Gradle build within Android Studio.

### Sample project

https://github.com/cheneric/retrolambda-androidlib-problem

### Environment

* OS X Yosemite 10.10.5
* Java 1.8.0_60
* Java 1.7.0_70
* Android Studio 1.4.1

**Comment by evant** [comment]
You sure your environment variables are being read correctly from Android Studio? Check out https://github.com/evant/gradle-retrolambda/issues/61

**Comment by cheneric** [comment]
Thanks.  That was the problem.  Works for me now!
