### ISSUE TITLE
Update to 2.0.6

### ISSUE THREAD

**Issue by konmik** [evant/gradle-retrolambda#150]
There is a crash fix in retrolambda, so I think it is a good idea to increase the plugin version as well.

**Comment by jaredsburrows** [comment]
+1

**Comment by jenzz** [comment]
:+1:

**Comment by evant** [comment]
I normally just wait until whenever my next release is since it's easy enough to set it yourself. Since `3.3.0` is taking such a long time though, I decided to push out `3.2.4` which bumps it up.
