### ISSUE TITLE
Breaks Instant Run

### ISSUE THREAD

**Issue by nealsanche** [evant/gradle-retrolambda#155]
Just pointing this out, and I know Android Studio 2.0 is just in preview release now, but Retrolambda seems to interfere with the Instant Run functionality. Any code written inside lambdas doesn't get updated during instant run.

**Comment by evant** [comment]
Are you seeing this issue on 3.2.4 and or 3.3.0-beta3? The latter uses the
transform api which would hopefully be compatible.

**Comment by nealsanche** [comment]
I'll check it out.

**Comment by nealsanche** [comment]
It was on 3.2.4 that I was seeing issues. I just tried 3.3.0-beta3, and it seems the issue is not present there. Awesome, thanks!

**Comment by vanniktech** [comment]
@evant could you try to explain what changed so that it does work with the 3.3.0-beta3? Could it be the transform API?

**Comment by nealsanche** [comment]
Though, doing more testing, I have found that something in 3.3.0-beta3 breaks my Espresso tests, sadly, so I guess I can't have the good stuff in this project yet.

**Comment by nealsanche** [comment]
I've uploaded my test app, where I'm trying to get Espresso to run with Retrolambda.

https://github.com/nealsanche/InstantUpdateTest

No idea why it'd just crash out with a NullPointerException.

**Comment by nealsanche** [comment]
It's not exactly Instant run related issues at this point though, I guess.

**Comment by evant** [comment]
Looks like the same issue as https://github.com/evant/gradle-retrolambda/issues/129#issuecomment-158652401 `3.3.0-SNAPSHOT` should work, I'll release another beta build at some point.

**Comment by nealsanche** [comment]
Yep, you're right. It's that testCoverageEnabled line. Simple case of adding too much stuff into gradle and not knowing what it'll break. Thanks.
