### ISSUE TITLE
Retrolambda 2.1.0 support: overcome command line length limits

### ISSUE THREAD

**Issue by orfjackal** [evant/gradle-retrolambda#159]
Retrolambda 2.1.0 added parameters -Dretrolambda.classpathFile and -Dretrolambda.includedFilesFile to avoid the command line length limit. The Gradle plugin should be updated to use them instead of the old parameters.

**Comment by tkhduracell** [comment]
Basic implementation here, https://github.com/evant/gradle-retrolambda/pull/160
Needs version check, and classpath usage

**Comment by Android-s14** [comment]
Any chance we can get a new release with the latest change? Thank you.

**Comment by athkalia** [comment]
the line length limit is causing us trouble as well. I'd love if you could push a new version with this asap

**Comment by evant** [comment]
Released `3.2.5` and `3.3.0-beta4` which include support for this.

**Comment by athkalia** [comment]
```
plugins {
    id "me.tatarka.retrolambda" version "3.2.5"
}
```

is complaining the the plugin version is wrong. The old plugin style declaration works with the new version though. Weird!

**Comment by evant** [comment]
Sorry, forgot to upload to gradle plugin portal. Only did maven central. Should be fixed now.
