### ISSUE TITLE
Setup problem?

### ISSUE THREAD

**Issue by mellson** [evant/gradle-retrolambda#17]
I keep getting this error in Android Studio 0.4.5

Execution failed for task ':app:patchAndroidJar'.

> Retrolambda: null/jre/lib/rt.jar does not exist, make sure that JAVE_HOME or retrolambda.jdk points to a valid version of java8
>    You can download java8 from https://jdk8.java.net/download.html

I have tried to follow your setup guidelines.
Java 8 is installed and both JAVA8_HOME and JAVA_HOME points to it.

Any ideas?

**Comment by yzp531** [comment]
like this 

apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'


retrolambda {
     jdk "C:/Java8/jdk1.8.0_45"
     oldJdk "C:/Java/jdk1.7.0_71"
     javaVersion JavaVersion.VERSION_1_7

    println("***************** ---------- *******************")
    println("JAVA_HOME: " + System.getenv("JAVA_HOME"))
    println("JAVA7_HOME: " + System.getenv("JAVA7_HOME"))
    println("JAVA8_HOME: " + System.getenv("JAVA8_HOME"))
    println("***************** ---------- *******************")
}
android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        disable 'InvalidPackage'
        abortOnError false
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compile 'com.android.support:support-v4:21.+'
    compile 'io.reactivex:rxjava:1.0.+'
    /* compile 'io.reactivex:rxandroid:0.23.+'*/
    compile 'com.squareup.retrofit:retrofit:1.8.+'
    compile 'com.squareup.okio:okio:1.1.+'
    compile 'com.squareup.okhttp:okhttp:2.1.+'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.1.+'
    compile 'de.keyboardsurfer.android.widget:crouton:1.8.5@jar'
    compile 'io.reactivex:rxandroid:0.24.0'
}

**Comment by growingdever** [comment]
It was really helpful.....

**Comment by Tsolmonbayar** [comment]
I keep getting this error in Android Studio 2.1

Execution failed for task ':app:patchAndroidJar'.

Retrolambda: null/jre/lib/rt.jar does not exist, make sure that JAVE_HOME or retrolambda.jdk points to a valid version of java8

Any ideas?
