### ISSUE TITLE
Breaks with TravisCI and CircleCI

### ISSUE THREAD

**Issue by AlokBansal8** [evant/gradle-retrolambda#172]
Both of these generate following message:

> Execution failed for task ':app:compileInternalDebugJavaWithJavac'.
> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

@evant please help.

**Comment by paulpv** [comment]
Something tells me this is a variant of #61.
If it is, as @evant recommends, hardcoding the path to JAVA8_HOME and JAVA7_HOME in a gradle.properties file seems like the simplest solution to this.

**Comment by PavelSynek** [comment]
Using `jdk: oraclejdk8` works for me on Travis.

**Comment by AlokBansal8** [comment]
@PavelSynek thanks :+1:
