### ISSUE TITLE
Is RetroLambda obsolete?

### ISSUE THREAD

**Issue by AlokBansal8** [evant/gradle-retrolambda#177]
With new Android Studio 2.1, do we need RetroLambda for using lambda functions in our code?

**Comment by evant** [comment]
Try it out, if it works for you great! It's pre-release software so I'd keep using gradle-retrolamba until N is out though.

**Comment by AlokBansal8** [comment]
I tried it. It is identifying the lambda functions and running them perfectly on my Marshmallow device.
