### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by HarshitMadhav** [evant/gradle-retrolambda#179]
please help I am facing this error and I am a beginner! please do help me !! the jdk version is in snapshot

![image](https://cloud.githubusercontent.com/assets/17410343/14326415/825bdd56-fc4b-11e5-8aa8-1eb07c54a386.png)
![untitled1](https://cloud.githubusercontent.com/assets/17410343/14326429/90c7cf9e-fc4b-11e5-8739-12e303b5c484.png)

**Comment by evant** [comment]
retrolamba isn't run for the layout preview, try changing your jdk to a java 8 version.

**Comment by HarshitMadhav** [comment]
Heartily Thank you for replying me!!

I have installed jdk java 8 version still I am having a error of this and I have set the environment variable with the name JAVA8_HOME
![untitled](https://cloud.githubusercontent.com/assets/17410343/14328668/5181012a-fc55-11e5-8165-3fd1af41b4e0.png)

**Comment by evant** [comment]
Have you set it as the jdk location in android studio? You might have to actually launch AS using it.

**Comment by HarshitMadhav** [comment]
yes sir I have set the path of AS to java!

**Comment by HarshitMadhav** [comment]
Yes sir my problem is resolved now!!

**Comment by HarshitMadhav** [comment]
Now there is some problem in opening main activity design screen!

**Comment by HarshitMadhav** [comment]
It shows some kind of error named as nullerrror exception!! what should  I do now?

**Comment by evant** [comment]
No idea, I'd advise asking somewhere like stackoverflow at this point, you'd probably get better help.

**Comment by HarshitMadhav** [comment]
I have choosed the second folder for the jdk
![untitled](https://cloud.githubusercontent.com/assets/17410343/14329809/cd81c674-fc5a-11e5-9753-e95e433e17db.png)

**Comment by HarshitMadhav** [comment]
the gradle and gradle sync is running fine but it is showing jdk error again

**Comment by HarshitMadhav** [comment]
Again I got stuck by this error!
![untitled](https://cloud.githubusercontent.com/assets/17410343/14466238/9006448a-00f3-11e6-9103-3886ecf640a7.png)

**Comment by evant** [comment]
I respectfully ask you to ask your question somewhere else. That error clearly has nothing to do with gradle-retrolambda and likely not even to do with java 8. Stackoverflow is a better forum for this kind of thing.

**Comment by HarshitMadhav** [comment]
Sorry for the inconvenience caused to you.. Actually I am using this github link of here to share pictures of my problems so that my friend could see it..

**Comment by HarshitMadhav** [comment]
![Uploading er.png…]()

**Comment by HarshitMadhav** [comment]
![har](https://cloud.githubusercontent.com/assets/17410343/14767661/041e889c-0a49-11e6-8f59-7546aa104ea4.png)
