### ISSUE TITLE
Retrolambda in library projects and main projects can't use lambdas.

### ISSUE THREAD

**Issue by ramanbranavitski** [evant/gradle-retrolambda#195]
Hi, I have a project with 2 modules(app and library). I add retrolambda as dependency to library project and it works fine. After that I add this library as dependency to my app module and I can't uses lamdas here. What can I do with this? Thanks.

**Comment by Undin** [comment]
You should add retrolambda dependency to main project too, because retrolambda is only gradle plugin but not a project dependency
