### ISSUE TITLE
Using the lambda expression cannot run the app through the real phone.

### ISSUE THREAD

**Issue by jun99999** [evant/gradle-retrolambda#202]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion '24.0.0'

    defaultConfig {
        applicationId "com.example.elixir.beaconversion23"
        minSdkVersion 19
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }
}
repositories {
    jcenter()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'org.altbeacon:android-beacon-library:2+'
    compile 'com.android.support:support-v4:24.1.1'
}

android{

    compileSdkVersion 24

    //buildToolsVersion "24rc2"
    buildToolsVersion "24.0.0"

    defaultConfig {

        jackOptions {
            enabled true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }}

buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'me.tatarka:gradle-retrolambda:3.2.5'
    }
}

// Required because retrolambda is on maven central
repositories {
    mavenCentral()
}

apply plugin: 'com.android.application' //or apply plugin: 'java'
apply plugin: 'me.tatarka.retrolambda'

![image](https://cloud.githubusercontent.com/assets/20786078/17323569/3c14eb9e-58d5-11e6-89f2-842cc3ecf720.png)

**Comment by Bartosz-Kozajda** [comment]
Just delete this:
```
jackOptions {
        enabled true
    }
```

**Comment by jun99999** [comment]
[image: Inline image 1]



Yes, thanks for your suggestion. After I delete it. Once I run, I need to
config this.
