### ISSUE TITLE
Error running in windows in incremental mode: generated command line is too long

### ISSUE THREAD

**Issue by orionlee** [evant/gradle-retrolambda#206]
The error is: 
```
 CreateProcess error=206, The filename or extension is too long
```

Rootcause:
- in incremental mode, the plugin passes the files to be processed in -Dretrolambda.includedFiles argument in the command line
- when there are numerous files to be processed, the generated command line exceeds windows limit on command line

Potential  solutions: 
- the plugin uses -Dretrolambda.includedFilesFile  (placing list of files in a file rather than on command line) instead
- if the number of files to be processed exceed certain limit, do not use incremental mode? 

See:
- Discussion on similar issues:  https://www.google.com/search?q=gradle+CreateProcess+error%3D206%2C+The+filename+or+extension+is+too+long

**Comment by evant** [comment]
The classpath and/or file change list are already written to a file if they are over a certain limit. Maybe this limit isn't tight enough? Can you post your command line that that is too long? (logic in https://github.com/evant/gradle-retrolambda/blob/master/gradle-retrolambda/src/main/groovy/me/tatarka/RetrolambdaExec.groovy)

**Comment by orionlee** [comment]
Hmm, In the relevant project the version of retrolambda is v3.2.4  (See [here](https://github.com/AntennaPod/AntennaPod/blob/1.6.1.2/build.gradle#L10).)

I cannot find `RetrolambdaExec.groovy` in tag v3.2.4 , even though 3.2.4 is quite recent.

**Comment by orionlee** [comment]
Edited excerpt from gradle run. 
```
Executing task ':core:compileRetrolambdaPlayDebug' (up-to-date check took 0.031 secs) due to:
  Input file C:\AP\core\build\retrolambda\playDebug\com\google\android\gms\base\R$drawable.class has been added.
  Input file C:\AP\core\build\retrolambda\playDebug\de\danoeh\antennapod\core\feed\FeedMedia$1.class has been added.
  Input file C:\AP\core\build\retrolambda\playDebug\de\danoeh\antennapod\core\service\GpodnetSyncService$1.class has been added.
Starting process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe''. 
Working directory: C:\AP\core 
Command: C:\Program Files\Java\jdk1.8.0_60\bin\java.exe -Dretrolambda.bytecodeVersion=50 
 -Dretrolambda.classpath=...(quite long but okay) 
 -Dretrolambda.includedFiles=C:.......(34k+ alone for -Dretrolambda.includedFiles)
```

Excerpts of -Dretrolambda.includedFiles= (total  394 classes):
```
C:\AP\core\build\retrolambda\playDebug\com\google\android\gms\base\R$drawable.class
C:\AP\core\build\retrolambda\playDebug\de\danoeh\antennapod\core\feed\FeedMedia$1.class
C:\AP\core\build\retrolambda\playDebug\de\danoeh\antennapod\core\service\GpodnetSyncService$1.class
...
C:\AP\core\build\retrolambda\playDebug\de\danoeh\antennapod\core\util\URLChecker.class
C:\AP\core\build\retrolambda\playDebug\de\danoeh\antennapod\core\util\id3reader\model\TagHeader.class
```

**Comment by evant** [comment]
It was added in `3.2.5` you should update.

**Comment by orionlee** [comment]
It looks like it is added in `3.3.0-beta` instead of `3.2.5` . Any catches /  concern on using 3.3.0, given it is still in beta?

Thanks

**Comment by evant** [comment]
A stable version of `3.3.0` was jut released yesterday. It really was in 'beta' far longer than it should have been. The only reason you wouldn't want to update is if you are using a really old version of the android gradle plugin (< 1.5.0). That said, it _was_ added in `3.2.5` but in https://github.com/evant/gradle-retrolambda/blob/v3.2.5/src/main/groovy/me/tatarka/RetrolambdaTask.groovy.

**Comment by orionlee** [comment]
Thanks for your prompt response
