### ISSUE TITLE
Call requires API level 19 (current min is 16): `java.util.Objects#requireNonNull`

### ISSUE THREAD

**Issue by vanniktech** [evant/gradle-retrolambda#225]
After updating from `'me.tatarka:gradle-retrolambda:3.2.5'` to `'me.tatarka:gradle-retrolambda:3.4.0'` lint complains:

> Call requires API level 19 (current min is 16): `java.util.Objects#requireNonNull`

**Comment by vanniktech** [comment]
Still happening with `3.6.0`.

**Comment by chemouna** [comment]
I'm having the same issue on 3.6.0 version also, lint is failing because of it.

**Comment by MyDogTom** [comment]
@vanniktech Are you still using `3.2.5` or have found any workaround? I receive the same lint error after including `error-prone` into project.

**Comment by vanniktech** [comment]
Moved on to Kotlin and the projects that are still having Lambdas are now all minSdk 19.

**Comment by PromanSEW** [comment]
I don't have this problem. minSdk = 15, gradle-retrolambda 3.6.0
Solution is waiting release of Android Studio 3.0, there are build-in support of Java 8 features in it

**Comment by MyDogTom** [comment]
I've found that in my case issue is not related to `Retrolambda`. `java.util.Objects#requireNonNull` is added automatically by `ErrorProne` compiler. In order to change this behavior, just add `-XDallowBetterNullChecks=false`
More details here: google/error-prone#375

**Comment by vanniktech** [comment]
Oh that might be the case since I'm using error prone. Guess this can be closed then.
