### ISSUE TITLE
Use retrolambda on some gradle tasks

### ISSUE THREAD

**Issue by flaghacker** [evant/gradle-retrolambda#232]
Is there a way to apply retrolambda only to one of the tasks? I want to provide both a jdk8 and jdk7 build of my library, and I would like to create separate tasks for those builds.

**Comment by evant** [comment]
Not really documented but you can call the retrolamda task directly. https://github.com/evant/gradle-retrolambda/blob/master/gradle-retrolambda/src/main/groovy/me/tatarka/RetrolambdaTask.groovy

**Comment by flaghacker** [comment]
@evant Looks like I finally have an excuse to learn Groovy, thanks for the help!
