### ISSUE TITLE
Why oldJdk?

### ISSUE THREAD

**Issue by bsideup** [evant/gradle-retrolambda#240]
Hi!

Why Gradle plugin requires oldJdk to be set?

Maven plugin works fine with only JDK 8 installed, is it something new in Retrolambda now yet supported in Gradle plugin?

Having two JDKs adds huge complexity to the project setup process :(

P.S. our project **is not for Android**, just a normal Java project with JDK 6 as a baseline

**Comment by evant** [comment]
See https://github.com/evant/gradle-retrolambda/issues/154

**Comment by bsideup** [comment]
@evant I'm not sure I see the answer there :) Wrong link or I miss something?

**Comment by evant** [comment]
It's discussion about removing oldJdk and running test with java 8 always. Note: you can always work around the issue by setting
```groovy
retrolambda {
  oldJdk = "/path/to/jdk8"
}
```

**Comment by bsideup** [comment]
@evant I'll try, thanks!

**Comment by evant** [comment]
Just released `2.6.0` that no longer requires `oldJdk` to be defined.
