### ISSUE TITLE
Missing tags for 3.6.0 and 3.6.1

### ISSUE THREAD

**Issue by szpak** [evant/gradle-retrolambda#248]
It seems that you might not push tags for 3.6.0 and 3.6.1 to GitHub: https://github.com/evant/gradle-retrolambda/releases . It can be somehow confusing in combination to not having release dates in CHANGELOG.md (#192).

**Comment by evant** [comment]
Sorry, forgot to push them. Should be fixed now. Dates in changelog is a good idea I'll do that when I get a chance.
