### ISSUE TITLE
Proguard still fails with retrolambda 2.5.1 targeting Java 7

### ISSUE THREAD

**Issue by Perseverance1139** [evant/gradle-retrolambda#251]
Proguard reports error for each lambda usage:
can't find referenced class java.lang.invoke.MethodHandles$Lookup
can't find referenced class java.lang.invoke.MethodHandles

Looking at this line here, I wonder should we remove methodhandles for Java 7 as well?
https://github.com/orfjackal/retrolambda/blob/6d5a4c1fd9d094452cfde2096a81ab82a0c1c9ce/retrolambda/src/main/java/net/orfjackal/retrolambda/Transformers.java#L116

Thanks!

**Comment by evant** [comment]
A couple of things: The README suggests adding `-dontwarn java.lang.invoke.*` to your proguard config, shouldn't this suppress that error? Secondly, if you think this change should be made, could you file it against https://github.com/orfjackal/retrolambda instead of this project?

**Comment by Perseverance1139** [comment]
Sorry about filing to the wrong project. My apologies...
