### ISSUE TITLE
AlertDialog OnClickListener not triggered

### ISSUE THREAD

**Issue by eric-grab** [evant/gradle-retrolambda#266]
the issue is only happening on certain devices e.g. Nexus 5 Emulator API 24

on those devices, the following does not work:
**SomeActivity.java**
```java
final AlertDialog.Builder builder = new AlertDialog.Builder(this);
                          builder.setPositiveButton(R.string.btn_im_ready, (dialogInterface, i) -> {
                    doSomething();// Not called!
                });
                builder.create().show();
```
Interestingly, this works:
**SomeActivity.java**
```java
final AlertDialog.Builder builder = new AlertDialog.Builder(this);
                          builder.setPositiveButton(R.string.btn_im_ready, (dialogInterface, i) -> {
                    SomeActivity.this.doSomething();// this is called!
                });
                builder.create().show();
```

Anyone with any ideas?

**Comment by evant** [comment]
Sounds like a potential retrolamda issue, make sure you are using the latest version and see if you can reproduce in a sample project. Having the outputed bytecode would also help.

**Comment by eric-grab** [comment]
My bad, it's our own issue, closing
