### ISSUE TITLE
Unsupport the jar with java8

### ISSUE THREAD

**Issue by cclover** [evant/gradle-retrolambda#282]
HI:

This plugin looks like do not support jar which build by java8.

I have a project, which dependency a jar compiled by java8.

When i build project with this plugin, it will show:

> Configure project :app
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:

**Comment by evant** [comment]
Correct, this plugin has never supported running on libs. I recommend switching to the official tools if possible as it does.
