### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by mradzinski** [evant/gradle-retrolambda#37]
Whenever adding the plugin to Android Studio I get:
Error:(2, 0) Cause: me/tatarka/RetrolambdaPlugin : Unsupported major.minor version 52.0

Andriod Studio 0.8.6
Gradle Build Tools 20.0.0

**Comment by Orabig** [comment]
I had this issue too, but making the JAVA_HOME point to JDK8 was not sufficient.
There is a (slightly hidden) parameter in Android Studio to change, hidden at **File->Other Settings->Default Project Structure->SDKs**
The solution was here : [http://stackoverflow.com/questions/16823790/android-studio-dont-know-where-is-java]
