### ISSUE TITLE
Android Studio accepts it, but compiler is confused

### ISSUE THREAD

**Issue by ber4444** [evant/gradle-retrolambda#39]
An exception has occurred in the compiler (1.8.0_11). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found

**Comment by trygvis** [comment]
I'm also running into this problem after I added the 'android-unit-test' plugin like this:

    apply plugin: 'android-unit-test'

    dependencies {
        ... existing dependencies ...

        testCompile 'junit:junit:4.11'
        testCompile 'org.robolectric:robolectric:2.4'
        testCompile 'org.easytesting:fest-assert:1.4'
    }

I can see that it is executing `org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler` with the SDKs android.jar: `-bootclasspath .../android-sdk-linux/platforms/android-19/android.jar`.

**Comment by evant** [comment]
If that classpath is correct then it is not using the patched android.jar which would explain the error (it's missing necessary classes from java 8). Maybe there is some interplay between the two plugins that is causing that.

**Comment by trygvis** [comment]
The path is correct in the way that it points to an existing jar in my Android SDK installation.

I guess it's my particular combination, but I would really like to get it to work :) Is there any other information I could give to help solve this issue?
