### ISSUE TITLE
Proguard fails with lambdas

### ISSUE THREAD

**Issue by NightRa** [evant/gradle-retrolambda#55]
For every lambda usage, proguard reports:

```
Warning: fj.F1Functions: can't find referenced class java.lang.invoke.MethodHandles$Lookup
Warning: fj.F1Functions: can't find referenced class java.lang.invoke.MethodHandles
```

(fj.F1Functions as an example)
As a note, I'm on using it on android.

**Comment by andresesfm** [comment]
I ran into this issue. The above proguard didn't work. However, the one in the README fixes the issue: `-dontwarn java.lang.invoke.*`
