### ISSUE TITLE
apt generated directory not found.

### ISSUE THREAD

**Issue by dbachelder** [evant/gradle-retrolambda#65]
gradle-retrolambda version 2.4.1 / android-apt 1.4 / android gradle (0.14.1) / tools 21.1.0

Suddenly we are seeing strange issues in our build process.. there are no diffs to any gradle files. 

However, we now see this:

```
:models:patchAndroidJar
:models:_compileReleaseJava
javac: directory not found: 
/projects/android/models/build/generated/source/apt/release
```

and this is the order of applied plugins:

```
apply plugin: 'com.android.library'
apply plugin: 'retrolambda'
apply plugin: 'android-apt'
```

Everything was working fine a few hours ago.. and checking out source to yesterday doesn't seem to help.  Is anyone else noticing bizarre issues today? Or am I completely nuts? I'm at a bit of a loss at the moment.

**Comment by ultraon** [comment]
I've got the same issue with retrolambda version 3.0.1, with version 2.5.0 - works good.

**Comment by JoanZapata** [comment]
@ultraon same thing here

**Comment by ian-ellis** [comment]
Happening here with 'me.tatarka:gradle-retrolambda:3.2.5'
