### ISSUE TITLE
Unused resources when used in Lambda expressions

### ISSUE THREAD

**Issue by maciejpigulski** [evant/gradle-retrolambda#69]
I have stumbled upon an issue while using retrolambda + Android + lint. Lint verification tool fails on finding strings referenced from string resources when that string is used in same place as a lambda expression. Simple example can be:

	AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
	builder.setMessage(R.string.message)
		.setPositiveButton(R.string.close, (dialog, which) -> {
			switch (which) {
				case DialogInterface.BUTTON_POSITIVE:
					dialog.dismiss();
					break;
			}	
		}).show();

This when running `./gradlew lint` will cause `R.string.close` produce a lint warning: `The resource R.string.close appears to be unused` and in my case fail the build. I could of course ignore that by using `tools:ignore` or pass Resources fetched String from outside the method call wherever I am using lambda expressions but that doesn't seem the right way. Code should be readable and short, this is the target of lambda expressions as well, so adding code to satisfy lint because of retrolambda seems like going against that principle. For instance this doesn't produce any warnings after adding `String string = getString(R.string.close)` and referencing it in `AlertDialog.Builder.setPositiveButton(...)`:

	AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
	String string = getString(R.string.close);
	builder.setMessage(getString(R.string.message, body.getError().getData()))
		.setPositiveButton(string, (dialog, which) -> {
			switch (which) {
				case DialogInterface.BUTTON_POSITIVE:
					dialog.dismiss();
					break;
			}	
		}).show();

**Comment by evant** [comment]
This is superseded by https://github.com/evant/gradle-retrolambda/issues/96 (and that there is now a workaround).
