### ISSUE TITLE
Can't make test work with v2.4.1 

### ISSUE THREAD

**Issue by mjurkus** [evant/gradle-retrolambda#73]
Hi,

I'm using your plugin (thanks for that by the way) v1.3.3 with my project. I also have tests running with https://github.com/novoda/gradle-android-test-plugin. 

Everything works fine and dandy. But I can't upgrade your plugin to 2.4.x. None of the tests compile then.

```
root
    -- application
    -- application-unit-tests
```

In my `application` project I have

```
retrolambda {
    jdk System.getenv("JAVA8_HOME")
    oldJdk System.getenv("JAVA7_HOME")
    javaVersion JavaVersion.VERSION_1_7
}
```

but I have no additional configuration in my `application-unit-tests` project. And not sure if I should since everything works fine with `v1.3.3`

**Comment by mjurkus** [comment]
Sorry for such delay. Tested on with 2.5.0 - same problems.

**Comment by evant** [comment]
Since google has released proper unit testing support, those testing plugins are now obsolete. I've made some changes in 3.0.0 that _may_ fix this issue, but moving to the native unit testing would be a better solution.

**Comment by mjurkus** [comment]
Were planing to migrate to native support this week so I'll follow up on this.

**Comment by mjurkus** [comment]
Works perfectly with native unit testing support.
