### ISSUE TITLE
Unsupported major.minor version 52.0 2.5.0

### ISSUE THREAD

**Issue by dbis01** [evant/gradle-retrolambda#74]
keep getting error in Android Studio 1.0.1

    buildscript {
        repositories {
            mavenCentral()
        }

        dependencies {
            classpath 'me.tatarka:gradle-retrolambda:2.5.0'
        }
    }

    repositories {
        mavenCentral()
    }

    apply plugin: 'com.android.application'
    apply plugin: 'me.tatarka.retrolambda'

    retrolambda {
        jdk System.getenv("JAVA8_HOME")
        oldJdk System.getenv("JAVA7_HOME")
        javaVersion JavaVersion.VERSION_1_7
        jvmArgs '-arg1', '-arg2'
    }

    android {
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }

        compileSdkVersion 21
        buildToolsVersion "21.1.1"

        defaultConfig {
            applicationId "com.aaa.bbb.android"
            minSdkVersion 15
            targetSdkVersion 21
            versionCode 1
            versionName "1.0"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.android.support:appcompat-v7:21.0.3'
    }

JAVA7_HOME=C:\Program Files\Java\jdk1.7.0_65
JAVA8_HOME=C:\Program Files\Java\jdk1.8.0_25
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_25

**Comment by tomkoptel** [comment]
Any progress on this issue?

I`m experiencing same problem on my Ubuntu machine:

## Environment
```bash
export JAVA_HOME="/usr/lib/jvm/java-7-oracle"
export JAVA6_HOME="/usr/lib/jvm/java-6-oracle"
export JAVA7_HOME="/usr/lib/jvm/java-7-oracle"
export JAVA8_HOME="/usr/lib/jvm/java-8-oracle"
```
## Gradle script

```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
        classpath 'me.tatarka:gradle-retrolambda:2.5.0'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'me.tatarka.retrolambda'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

retrolambda {
    jdk System.getenv("JAVA8_HOME")
    oldJdk System.getenv("JAVA6_HOME")
    javaVersion JavaVersion.VERSION_1_6
}

dependencies {
    compile project(":rest")
    compile 'com.jakewharton.timber:timber:2.5.0'
    compile 'io.reactivex:rxandroid:0.23.0'
    compile 'com.squareup.retrofit:retrofit:1.8.0'
}

```

Any explanation what does this message really mean?

**Comment by bennythomps** [comment]
Just a heads up, it was as simple as changing the SDK path in project settings to point to my JDK 8 home directory.  I had started my project before including this plugin and was at that pointed to 7, but during setup for this library installed 8, but didn't update my project settings.  Updating the path fixed the issue for me.  HTH

**Comment by fada21** [comment]
@tomkoptel Have you changed SDK path in project settings as @bennythomps said? I've posted previously an image with hint how it should look like.

**Comment by tomkoptel** [comment]
Yep, that helped me :) 

At the moment I'm using `Android Studio 1.0.2`. Also, I've launched studio from console command by launching sh script so that idea could properly pick environment variables.

```bash
./your_location/android-studio/bin/studio.sh &
```

 Though the final step was changing JDK location in module settings in Android Studio as suggested @fada21.

**Comment by hamidp** [comment]
For us the issue was a java-library that was part of an Android project. For whatever reason it believed it was jdk 6, and the sdk wasn't around. There definitely should more logging around failures in the plugin itself but we were able to get things running by adding this to the library:

```
retrolambda {
    javaVersion JavaVersion.VERSION_1_7
}
```

**Comment by hamidp** [comment]
On top of making sure `JAVA_HOME` was not set.

**Comment by magicgoose** [comment]
I fixed this by changing module's Java SDK path to JDK *8

**Comment by hamen** [comment]
Hi all
FYI, It's happening randomly for a couple of weeks now. I can get rid of it only adding

```groovy
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home
```

to my `gradle.properties`. `JAVA_HOME` and `JAVA8_HOME` are properly set too.
Ivan

**Comment by dbachelder** [comment]
@hamen thanks, that worked...

**Comment by bytehala** [comment]
@magicgoose Your solution worked. Cheers!

**Comment by prt2121** [comment]
setting org.gradle.java.home works for me.
Thanks @hamen

**Comment by IlyaEremin** [comment]
@hamen I set java.home in gradle.properties, but face with new problem: `Fatal Error: Unable to find package java.lang in classpath or bootclasspath`
Retrolambda is convenient, but sometimes drives me crazy

**Comment by alcarvalho** [comment]
For me the only thing that worked was setting adding:

`gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`

To `idea.properties` file. In my case it lives here:

`/Applications/IntelliJ IDEA 14.app/Contents/bin/idea.properties`

And then, restart IntelliJ, obviously.

I have found this [here](http://dmitrijs.artjomenko.com/2014/02/setting-different-javahome-for-gradle.html).

I am a Mac OS X (10.9 - Mavericks) user.

If you want to automatically update all your IntelliJs installations, I have made a script to do so here:
https://gist.github.com/alcarvalho/26fb041de96f6cf30e91

Note that if you ever update your jdk 8 version, you should update the file as well.

**Comment by paulirotta** [comment]
On Windows (and others) try Project Structure, JDK location
C:\Program Files\Java\jdk1.8.0_40

**Comment by evant** [comment]
Sorry for the delay, but I think I got to the bottom to this. The latest version of gradle-retrolambda was compiled with java 8, making it not work if you ran gradle with a lower java version. All the workarounds above ensure that you are running gradle with java 8.

Since my intention was to allow you to run gradle with a lower java version (as long as it can find java 8 to actually compile your source code), this will be fixed in the next version.

**Comment by evant** [comment]
Fixed in 3.0.0

**Comment by kolipass** [comment]
I have the trable (``` Unsupported major.minor version 52.0```) in fresh version ```classpath 'me.tatarka:gradle-retrolambda:3.2.3'```. What did i do wrong? There is my gist https://gist.github.com/kolipass/ebaa82476a89946e0505 .

I try to use  ```jvmArgs '-noverify'``` and _projectlombok_ then i have ```lombok/ast/Node : Unsupported major.minor version 52.0``` If i didn't use _projectlombok_ i received ```java.lang.UnsupportedClassVersionError Unsupported major.minor version 52.0``` for every test.

**Comment by TriplEight** [comment]
Also be sure you are not using "**Android version to use when rendering layouts in IDE**" button with **Andriod N (preview)** set, choose another version.

**Comment by CRomeo8294** [comment]
I solved this by installing Java 8 and changing the JDK location to the new Java 8, rebuilt gradle and everything worked perfectly.

**Comment by shantanucse18** [comment]
Unset JAVA_HOME and JAVA8_HOME, set JDK8 path in Android studio project settings. Restart android studio if you unset JAVA_HOME while android studio is running.

**Comment by lozery** [comment]
[You must run and compile your application with the same version of Java.](http://stackoverflow.com/a/29176500)
 check this

**Comment by magicgoose** [comment]
@lozery
> If you're using Eclipse
wait what? someone does still use it for Android development?

**Comment by yogieeka** [comment]
Change build gradle version it's work for me
before:
-classpath 'com.android.tools.build:gradle:2.2.0'
after:
-classpath 'com.android.tools.build:gradle:2.1.3'

**Comment by sangeetagrover-kiwi** [comment]
I also faced the same problem, it can be solved by following two steps:

Step 1: Download Java 8.
Step 2: Update Android Studio to the latest version 2.2.

**Comment by paulirotta** [comment]
Note that current Anndroid tools/google libraries require JDK8 or you will get "Unsupported major.minor version 52.0". This is true even if you are not using Retrolambda.

**Comment by ViliusKraujutis** [comment]
Adding this line to `gradle.properties` file, solved the issue:

```
org.gradle.java.home=/usr/java/jdk1.8.0_45/
```

**Comment by liuliangsir2016** [comment]
I met this issue too

**Comment by HandokoTjung** [comment]
Go to File --> other setting --> Default project structure... --> check the check box of use embedded jdk
![image](https://cloud.githubusercontent.com/assets/16622664/25287862/45db5474-26ed-11e7-8d65-191519bca019.png)
cheers^^

**Comment by fineday009** [comment]
I was wondering if Java7 works  in the issue.  It does not work in my win7/JDK1.7, anyone knows?

**Comment by ebrian** [comment]
For me I just had to restart Android Studio, lol.

**Comment by sujeet123** [comment]
Hi All,

I was also facing same issue:
Error:(1, 1) A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

I just updated JDK location on below setting(from "JDK 1.7" to "C:\Program Files\Android\Android Studio\" and select the check box for Embedded JDK).

File->Other Settings=>Default Project Struture
