### ISSUE TITLE
If I use this plugin in my project, the IntelliJ IDEA project cannot be generated with library dependencies.

### ISSUE THREAD

**Issue by molikto** [evant/gradle-retrolambda#77]
newest IntelliJ IDEA version

**Comment by pvg-alex** [comment]
Is it related to https://github.com/evant/gradle-retrolambda/issues/15 ? Seems like I'm facing the same issue. How can we try the fix, that was announced in that post?

**Comment by evant** [comment]
@pvg-alex the fix in #15 has been in the plugin for quite a long time now. Are you applying the plugin to the library projects as well?

**Comment by evant** [comment]
Closing for lack of information, feel free to reopen if you are still having issues.
