### ISSUE TITLE
Google Play Services 6.5+ compatibility

### ISSUE THREAD

**Issue by jbarr21** [evant/gradle-retrolambda#79]
I'm doing some Android Wear development and was researching if [Google Play Services 6.5](http://developer.android.com/google/play-services/setup.html#Setup) with its separate dependencies still create issues with this plugin like the Readme speaks of in the [known issues](https://github.com/evant/gradle-retrolambda#using-google-play-services-causes-retrolambda-to-fail). From what I've read, the issue stemmed from [incompatible byte code](https://github.com/orfjackal/retrolambda/issues/25#issuecomment-50001683) in the SupportMapFragment class. I noticed that that issue was closed. Also, when I included Google Play Services 6.5 and used a SupportMapFragment, I did not get any compilation errors.  Has anyone else had issues with this plugin and Google Play Services 6.5+?  If not, it might be worth mentioning in the known issues that the issue is resolved.

**Comment by evant** [comment]
Added a note in the README that newer versions should fix this.

**Comment by vkotovv** [comment]
Are Google Play services 8+ supported now?
