### ISSUE TITLE
Consider supporting method references?

### ISSUE THREAD

**Issue by cherrydev** [evant/gradle-retrolambda#89]
Since method references ( object::method ) are closely related to lambda expressions, have you considered supporting them in retrolambda?

**Comment by evant** [comment]
You should ask this under [retrolamda](https://github.com/orfjackal/retrolambda). This is **only** for the cradle plugin.

**Comment by cherrydev** [comment]
Thanks!

**Comment by cherrydev** [comment]
According to this issue: https://github.com/orfjackal/retrolambda/issues/17 method references SHOULD work.  When I tried it, I got a NPE at the site of the assignment:

```
private Runnable myThing = mField::method
```

**Comment by evant** [comment]
You should open an issue there then. It's *very* unlikely this plugin is the cause. You should try to minimize it to a small sample project that reproduces it.

**Comment by cypressious** [comment]
I'm pretty sure method references already work. Make sure ```mField``` is not null itself.

**Comment by evant** [comment]
I'm going to assume that there is no issue here.
