### ISSUE TITLE
Build exception: cannot call Task.setEnabled(boolean) after task has started execution

### ISSUE THREAD

**Issue by dlew** [evant/gradle-retrolambda#94]
While attempting to upgrade to retrolambda 3.0.0 (from 2.5.0) I've run into this error a bunch of times:

`Cannot call Task.setEnabled(boolean) on task ':trello-wear-shared:compileRetrolambdaRelease' after task has started execution.`

It doesn't always happen; cleaning the build seems to fix it. But on the next build the task gets run again (even though it ought to be up-to-date) and then this happens. Maybe it should be using `StopExecutionException` instead of `setEnabled`?

I hate to create an issue where I don't know why it's happening or how to repro, but I've run out of ideas.

**Comment by evant** [comment]
I actually think I know what's causing this. Will try to look for a workaround.

**Comment by evant** [comment]
Ok, so I know _where_ this is happening, but I can't reproduce it. What version of gradle are you running, maybe something has changed? I implemented the fix you suggested (replacing `enabled = false` with `throw new StopExecutionException()`). If you want to test if that fixes it you can get version `3.0.1-SNAPSHOT` from the the sonatype snapshots repo (`https://oss.sonatype.org/content/repositories/snapshots/`)

**Comment by dlew** [comment]
We're using Gradle 2.2.1.

I'll check to see if this fixes the problem when I've got time tomorrow.

**Comment by dlew** [comment]
I just tested it out - went from a failing build (using 3.0.0) to a successful build (using the 3.0.1-SNAPSHOT).

**Comment by SleeplessByte** [comment]
I am running into the same problem and I have added the maven snapshot but for some reason it's not using the metadata file to get the actual snapshot. 

Tried to revert: 2.5.0 is now returning
`Error:(19, 0) Cause: me/tatarka/RetrolambdaPlugin : Unsupported major.minor version 52.0`

**Comment by evant** [comment]
@SleeplessByte I'll release the snapshot soon, in the meantime check out #74 for the cause/workarounds for `Unsupported major.minor version 52.0`

**Comment by SleeplessByte** [comment]
@evant just on a side note. 

- Changed buildscript dep to 3.+ and it now does find some 3. version.
- Regular dep: `retrolambdaConfig files( '../gradle-retrolambda-3.0.1.jar')` downloaded from the snapshot repo
- Build: Now fails on proguard. Any class with a lambda says "can't find referenced class" and all references to R of all modules are broken.

**Comment by evant** [comment]
@SleeplessByte If you are running into any other issue, please open a separate issue. Though, `retrolambdaConfig files( '../gradle-retrolambda-3.0.1.jar')` doesn't look right to me. `retrolambdaConfig` is for configuring the retrolambda jar you are using (which is at 2.0.0 at the moment), you shouldn't be passing anything about the gradle plugin to it.

**Comment by evant** [comment]
Fixed in 3.0.1

**Comment by SleeplessByte** [comment]
Makes sense. All working now :)
