### ISSUE TITLE
Need to reopen issue #65 for version 3.0.1. Compatibility with apt-plugin

### ISSUE THREAD

**Issue by ultraon** [evant/gradle-retrolambda#98]

**Comment by evant** [comment]
The project now has a sample app with the apt-plugin. Could you try running it and see if you run into the same issue? If not, could you try to figure out what might be different?

**Comment by ultraon** [comment]
@evant I took your android sample application, made separate project with your code, i used dagger 2 release (instead SNAPSHOT) and connected retrolambda via repository (not from your project source). After first successful compilation i made clean project and then i got following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:_compileDebugJava'.
> directory not found: /Users/vitaliypopov/Develop/projects_a/TestRetroLambda/app/build/generated/source/apt/debug
```

**Comment by ultraon** [comment]
@evant And i found solution, in build.gradle apply plugin section should be next:

```
apply plugin: 'com.android.library'
apply plugin: 'android-apt'
apply plugin: 'me.tatarka.retrolambda'
```
With this order it works well (first android-apt, i have v.1.4, then me.tatarka.retrolambda, i have version 3.0.1). With old version retrolambda (v. 2.5.0) there wasn't this issue.

**Comment by evant** [comment]
Ah alright, I expanded my android-apt fix in 3.0 to better handle other possible changes to the javaCompile task by other plugins. However, this made it more dependent or ordering than it was before. I'll make sure to add a note to the README and changelog about this.

**Comment by ultraon** [comment]
Ok, thank you very much!

**Comment by evant** [comment]
Alright, they have been updated.
