### ISSUE TITLE
cant see java8_home

### ISSUE THREAD

**Issue by gc986** [evant/gradle-retrolambda#99]
I use "me.tatarka:gradle-retrolambda:3.0.1". When compiling I receive this error:

> Error:Execution failed for task ':app:_compileDebugJava'.
> When running gradle with java 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

In the system (Ubuntu) lists all variables, variable JAVA8_HOME has the following value:
JAVA8_HOME=/usr/lib/jvm/java-8-oracle
How to resolve this situation?

**Comment by ultraon** [comment]
@gc986 first of all put this code to your build.gradle main module:
```groovy
retrolambda {
    println("***************** ---------- *******************")
    println("JAVA_HOME: " + System.getenv("JAVA_HOME"))
    println("JAVA7_HOME: " + System.getenv("JAVA7_HOME"))
    println("JAVA8_HOME: " + System.getenv("JAVA8_HOME"))
    println("***************** ---------- *******************")
}
```

And while rebuild your project see gradle log in console (check for correct pathes for JAVA_... from System.getenv(...)).

**Comment by gc986** [comment]
My system only sees JAVA_HOME, other variables did not see. Although "env" command prints out all the variables correctly. Will try register variables in system.

**Comment by gc986** [comment]
In "Ubuntu" you need edit files "/etc/profile.d/jdk.csh" and "/etc/profile.d/jdk.sh"
My files - jdk.csh:
>setenv J2SDKDIR /usr/lib/jvm/java-8-oracle
>setenv J2REDIR /usr/lib/jvm/java-8-oracle/jre
>setenv PATH ${PATH}:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
>setenv JAVA_HOME /usr/lib/jvm/java-8-oracle
>setenv DERBY_HOME /usr/lib/jvm/java-8-oracle/db

>setenv JAVA6_HOME /usr/lib/jvm/java-6-openjdk-amd64
>setenv JAVA7_HOME /usr/lib/jvm/java-7-openjdk-amd64
>setenv JAVA8_HOME /usr/lib/jvm/java-8-oracle

jdk.sh:
>export J2SDKDIR=/usr/lib/jvm/java-8-oracle
>export J2REDIR=/usr/lib/jvm/java-8-oracle/jre
>export PATH=$PATH:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
>export JAVA_HOME=/usr/lib/jvm/java-8-oracle
>export DERBY_HOME=/usr/lib/jvm/java-8-oracle/db
>export JAVA6_HOME=/usr/lib/jvm/java-6-openjdk-amd64
>export JAVA7_HOME=/usr/lib/jvm/java-7-openjdk-amd64
>export JAVA8_HOME=/usr/lib/jvm/java-8-oracle

**Comment by johnsonc** [comment]
Also seen in Windows...    Any workaround?

The system variables are not seen except JAVA_HOME.
    println("JAVA_HOME: " + System.getenv("JAVA_HOME"))
    println("JAVA7_HOME: " + System.getenv("JAVA7_HOME"))
    println("JAVA8_HOME: " + System.getenv("JAVA8_HOME"))
    println("TEMP: " + System.getenv("TEMP"))
    println("WEIRD: " + System.getenv("WIERD"))

Gives: 

JAVA_HOME: C:\Program Files\Java\jdk1.8.0_45
JAVA7_HOME: null
JAVA8_HOME: null
TEMP: C:\Users\Johnny\AppData\Local\Temp
WEIRD: null


JAVA8_HOME contains the exact same value as JAVA_HOME btw..

**Comment by mosteo** [comment]
Workaround adding to build.gradle (app module):

retrolambda {
    jdk '/usr/lib/jvm/java-8-oracle/' // Or whatever path you have
}

**Comment by yogeshmishrikotkar** [comment]
I am also facing same issue on windows machine, can any one help?

**Comment by yogeshmishrikotkar** [comment]
This is my  build.gradle. I tried setting the path of jdk in environment variable as JAVA8_HOME as well but getting same path for java home and java8 home 




apply plugin: 'com.android.application'

/* 1) Apply the Gradle Retrolambda Plugin */
apply plugin: 'me.tatarka.retrolambda'
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.0"

    defaultConfig {
        applicationId "com. mypackage"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }



    /* 2) Compile for Java 1.8 or greater */
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    /* 3) Exclude duplicate licenses */
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/DEPENDENCIES'
        pickFirst 'AndroidManifest.xml'
    }
}
dependencies {
    /*compile fileTree(dir: 'libs', include: ['*.jar'])*/
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
   
 
}



retrolambda {
    jdk  getenv("JAVA8_HOME")
    oldJdk  getenv("JAVA6_HOME")
    javaVersion JavaVersion.VERSION_1_6
    jvmArgs '-arg1', '-arg2'
    defaultMethods false
    incremental true
}

**Comment by adamsp** [comment]
For future Googlers; you can forward your env vars from OS X to Android Studio by adding the following to your `.bash_profile` after you've set the vars:

```
launchctl setenv JAVA8_HOME $JAVA8_HOME JAVA7_HOME $JAVA7_HOME JAVA_HOME $JAVA_HOME
```
